<?php
define("SALT1","wtSHSU890381IC4");
define("SALT2","4CITAcywut46a");
define("SITE","http://localhost/hotel");
define("HOST","localhost");
define("USER","root");
define("PASSWORD","");
define("DATABASE","hotel");
define("SECRET","gfhUi34xVbds23Qgk");
?>